import type { Metadata } from "next";
import { Inconsolata } from "next/font/google";
import Navbar from "../components/admin-ui/Navbar/Navbar";

const inconsolata = Inconsolata({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-black min-h-screen flex">
        <Navbar />
        {/* {children} */}
        <div className="bg-white flex-grow mt-2 mr-2 mb-2 rounded-lg p-4">

        </div>
    </div>
  );
}
